// App.tsx
import React from 'react'
import { Home } from './Home'
import { Practice } from './Practice'

export const App = () => {
  const [showHome, setShowHome] = React.useState(true)
  const [chosenChords, setChosenChords] = React.useState([])

  function addChords(event) {
    if (event.target.tagName === 'BUTTON') {
      setChosenChords([...chosenChords, event.target.innerText])
    }
  }

  return (
    <header>
      {showHome ? (
        <Home
          start={() => {
            setShowHome(false)
          }}
          chosenChords={chosenChords}
          addChords={addChords}
        />
      ) : (
        <Practice chosenChords={chosenChords} />
      )}
    </header>
  )
}

// App.svelte
<script>
  import Home from './Home.svelte'
  import Practice from './Practice.svelte'

  let showHome = true
  let chosenChords = []

  function addChords(event) {
    if (event.target.tagName === 'BUTTON') {
      chosenChords = [...chosenChords, event.target.innerText]
    }
  }
</script>

<style>

</style>

<header>
  {#if showHome}
    <h1>GuitBetter</h1>
    <Home
      start={() => {
        showHome = false
      }}
      {chosenChords}
      {addChords} />
  {:else}
    <Practice {chosenChords} />
  {/if}
</header>
